services:
  api:
    build: .
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoramento/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:12.1.0
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoramento/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoramento/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
